
DROP TABLE IF EXISTS requests CASCADE;
DROP TABLE IF EXISTS apartments CASCADE;
DROP TABLE IF EXISTS buildings CASCADE;
DROP TABLE IF EXISTS addresses CASCADE;
DROP TABLE IF EXISTS locations CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    jmbg VARCHAR(13) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    surname VARCHAR(100) NOT NULL,
    phone_number VARCHAR(30) NOT NULL,
    user_type VARCHAR(20) NOT NULL --'Administrator', 'Resident', 'Manager'
);

CREATE TABLE locations (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    city VARCHAR(200) NOT NULL,
    country VARCHAR(200) NOT NULL
);

CREATE TABLE addresses (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    street VARCHAR(200) NOT NULL,
    number INT NOT NULL
);

CREATE TABLE buildings (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    building_code VARCHAR(50) NOT NULL UNIQUE,
    neighbourhood VARCHAR(150) NOT NULL,
    address_id BIGINT NOT NULL,
    location_id BIGINT NOT NULL,
    number_of_floors INT NOT NULL,
    manager_jmbg VARCHAR(13) NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'Pending', -- 'Pending', 'Approved', 'Rejected'
    FOREIGN KEY (address_id) REFERENCES addresses(id),
    FOREIGN KEY (location_id) REFERENCES locations(id),
    FOREIGN KEY (manager_jmbg) REFERENCES users(jmbg) ON DELETE SET NULL
);

CREATE TABLE apartments (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    apartment_number INT NOT NULL,
    description TEXT NOT NULL,
    number_of_rooms INT NOT NULL,
    max_number_of_residents INT NOT NULL,
    building_id BIGINT NOT NULL,
    UNIQUE (apartment_number, building_id),
    FOREIGN KEY (building_id) REFERENCES buildings(id) ON DELETE CASCADE
);

CREATE TABLE requests (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    building_id BIGINT NOT NULL,
    apartment_number INT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    status VARCHAR(20) NOT NULL, -- Pending, Approved, Rejected
    rejection_reason TEXT NULL,
    handled_by BIGINT NULL,      -- manager user id who handled the request
    handled_at TIMESTAMP NULL,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (building_id) REFERENCES buildings(id),
    FOREIGN KEY (handled_by) REFERENCES users(id)
);


