CREATE TABLE users (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    jmbg VARCHAR(13) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    surname VARCHAR(100) NOT NULL,
    phone_number VARCHAR(30) NOT NULL,
    user_type VARCHAR(20) NOT NULL --'Administrator', 'Resident', 'Manager'
);

CREATE TABLE locations (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    city VARCHAR(200) NOT NULL,
    country VARCHAR(200) NOT NULL
);

CREATE TABLE addresses (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    street VARCHAR(200) NOT NULL,
    number INT NOT NULL
);

CREATE TABLE buildings (
    id VARCHAR(50) PRIMARY KEY,
    address_id BIGINT NOT NULL,
    neighbourhood VARCHAR(150) NOT NULL,
    location_id BIGINT NOT NULL,
    number_of_floors INT NOT NULL,
    manager_jmbg VARCHAR(13) NULL,
    FOREIGN KEY (address_id) REFERENCES addresses(id),
    FOREIGN KEY (location_id) REFERENCES locations(id),
    FOREIGN KEY (manager_jmbg) REFERENCES users(jmbg) ON DELETE SET NULL
);

CREATE TABLE apartments (
    id INT NOT NULL,
    description TEXT NOT NULL,
    number_of_rooms INT NOT NULL,
    max_number_of_residents INT NOT NULL,
    building_id VARCHAR(50) NOT NULL,
    PRIMARY KEY (id, building_id),
    FOREIGN KEY (building_id) REFERENCES buildings(id) ON DELETE CASCADE
);
